import { TimeZone } from '@/types';

export const POPULAR_TIMEZONES: TimeZone[] = [
  {
    id: 'America/New_York',
    name: 'Eastern Time',
    city: 'New York',
    country: 'United States',
    offset: 'UTC-5/-4',
    abbreviation: 'EST/EDT',
    isDST: true,
  },
  {
    id: 'America/Los_Angeles',
    name: 'Pacific Time',
    city: 'Los Angeles',
    country: 'United States',
    offset: 'UTC-8/-7',
    abbreviation: 'PST/PDT',
    isDST: true,
  },
  {
    id: 'Europe/London',
    name: 'Greenwich Mean Time',
    city: 'London',
    country: 'United Kingdom',
    offset: 'UTC+0/+1',
    abbreviation: 'GMT/BST',
    isDST: true,
  },
  {
    id: 'Europe/Paris',
    name: 'Central European Time',
    city: 'Paris',
    country: 'France',
    offset: 'UTC+1/+2',
    abbreviation: 'CET/CEST',
    isDST: true,
  },
  {
    id: 'Asia/Tokyo',
    name: 'Japan Standard Time',
    city: 'Tokyo',
    country: 'Japan',
    offset: 'UTC+9',
    abbreviation: 'JST',
    isDST: false,
  },
  {
    id: 'Asia/Shanghai',
    name: 'China Standard Time',
    city: 'Shanghai',
    country: 'China',
    offset: 'UTC+8',
    abbreviation: 'CST',
    isDST: false,
  },
  {
    id: 'Asia/Dubai',
    name: 'Gulf Standard Time',
    city: 'Dubai',
    country: 'UAE',
    offset: 'UTC+4',
    abbreviation: 'GST',
    isDST: false,
  },
  {
    id: 'Australia/Sydney',
    name: 'Australian Eastern Time',
    city: 'Sydney',
    country: 'Australia',
    offset: 'UTC+10/+11',
    abbreviation: 'AEST/AEDT',
    isDST: true,
  },
  {
    id: 'America/Chicago',
    name: 'Central Time',
    city: 'Chicago',
    country: 'United States',
    offset: 'UTC-6/-5',
    abbreviation: 'CST/CDT',
    isDST: true,
  },
  {
    id: 'America/Denver',
    name: 'Mountain Time',
    city: 'Denver',
    country: 'United States',
    offset: 'UTC-7/-6',
    abbreviation: 'MST/MDT',
    isDST: true,
  },
  {
    id: 'Europe/Berlin',
    name: 'Central European Time',
    city: 'Berlin',
    country: 'Germany',
    offset: 'UTC+1/+2',
    abbreviation: 'CET/CEST',
    isDST: true,
  },
  {
    id: 'Asia/Singapore',
    name: 'Singapore Standard Time',
    city: 'Singapore',
    country: 'Singapore',
    offset: 'UTC+8',
    abbreviation: 'SGT',
    isDST: false,
  },
  {
    id: 'Asia/Hong_Kong',
    name: 'Hong Kong Time',
    city: 'Hong Kong',
    country: 'Hong Kong',
    offset: 'UTC+8',
    abbreviation: 'HKT',
    isDST: false,
  },
  {
    id: 'Europe/Moscow',
    name: 'Moscow Time',
    city: 'Moscow',
    country: 'Russia',
    offset: 'UTC+3',
    abbreviation: 'MSK',
    isDST: false,
  },
  {
    id: 'America/Sao_Paulo',
    name: 'Brasília Time',
    city: 'São Paulo',
    country: 'Brazil',
    offset: 'UTC-3',
    abbreviation: 'BRT',
    isDST: false,
  },
  {
    id: 'Asia/Kolkata',
    name: 'India Standard Time',
    city: 'Mumbai',
    country: 'India',
    offset: 'UTC+5:30',
    abbreviation: 'IST',
    isDST: false,
  },
  {
    id: 'Asia/Seoul',
    name: 'Korea Standard Time',
    city: 'Seoul',
    country: 'South Korea',
    offset: 'UTC+9',
    abbreviation: 'KST',
    isDST: false,
  },
  {
    id: 'America/Toronto',
    name: 'Eastern Time',
    city: 'Toronto',
    country: 'Canada',
    offset: 'UTC-5/-4',
    abbreviation: 'EST/EDT',
    isDST: true,
  },
  {
    id: 'Europe/Stockholm',
    name: 'Central European Time',
    city: 'Stockholm',
    country: 'Sweden',
    offset: 'UTC+1/+2',
    abbreviation: 'CET/CEST',
    isDST: true,
  },
  {
    id: 'Africa/Cairo',
    name: 'Eastern European Time',
    city: 'Cairo',
    country: 'Egypt',
    offset: 'UTC+2',
    abbreviation: 'EET',
    isDST: false,
  },
];